name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Test
      run: go test -v ./...

    - name: Make release
      run: |
        chmox u+x build.sh
        ./build.sh ${{ github.event.head_commit.message }}

    - name: Build binary
      run: GOOS=linux GOARCH=amd64 go build -o goo .
