name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Build tooling binary
      run: make build-tooling

    - name: Run tests
      run: make test

    - name: Build binary
      run: ./build_tool '${{ github.event.head_commit.message }}'

    - name: Make release
      uses: actions/upload-artifact@v4
      with: 
        name: test_artifact
        path: ./goo
