name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Test
      run: go test -v ./...

    - name: Build binary
      run: GOOS=linux GOARCH=amd64 go build -o goo .

    - name: Make release
      if: contains( ${{ github.event.head_commit.message }}, 'release' ) == false
      run: echo 'We aint releasing this one '
